<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Notice;
use Carbon\Carbon;

class NoticeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing notices
        Notice::truncate();

        $notices = [
            // ===================== URGENT NOTICES =====================
            [
                'title' => '⚠️ URGENT: Scholarship Application Deadline Extended',
                'content' => 'We are pleased to announce that the scholarship application deadline has been extended to December 31, 2024. This extension gives students more time to prepare and submit their applications. All eligible candidates are encouraged to apply before the new deadline. For more information, please contact the admissions office.',
                'type' => 'urgent',
                'priority' => 'urgent',
                'status' => 'published',
                'is_pinned' => true,
                'published_at' => Carbon::now()->subDays(2),
                'expires_at' => Carbon::now()->addDays(30),
                'file_paths' => json_encode(['notices/2024/12/scholarship-guide.pdf']),
                'file_names' => json_encode(['Scholarship_Guide_2024.pdf']),
                'views' => 245,
                'downloads' => 89,
            ],
            [
                'title' => '📢 Important: New Academic Year Registration',
                'content' => 'Registration for the new academic year 2024-2025 is now open. All students must complete their registration by January 15, 2025. Please ensure you have submitted all required documents and paid the registration fees. Late registrations will be subject to a penalty fee. For assistance, visit the student services office.',
                'type' => 'important',
                'priority' => 'high',
                'status' => 'published',
                'is_pinned' => true,
                'published_at' => Carbon::now()->subDays(5),
                'expires_at' => Carbon::now()->addDays(25),
                'file_paths' => json_encode(['notices/2024/12/registration-form.pdf', 'notices/2024/12/fee-structure.xlsx']),
                'file_names' => json_encode(['Registration_Form_2024.pdf', 'Fee_Structure_2024.xlsx']),
                'views' => 189,
                'downloads' => 67,
            ],
            [
                'title' => '🎓 Congratulations: Graduation Ceremony 2024',
                'content' => 'The annual graduation ceremony for the class of 2024 will be held on February 28, 2025 at the Grand Convention Hall. All graduating students are required to confirm their attendance by February 10, 2025. Guest passes are limited and available on a first-come, first-served basis. We look forward to celebrating this milestone with you!',
                'type' => 'event',
                'priority' => 'high',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(10),
                'expires_at' => Carbon::now()->addDays(40),
                'file_paths' => json_encode(['notices/2024/12/graduation-schedule.pdf']),
                'file_names' => json_encode(['Graduation_Schedule_2024.pdf']),
                'views' => 156,
                'downloads' => 45,
            ],
            [
                'title' => '📚 Library Hours Extended During Exams',
                'content' => 'To support students during the upcoming examination period, the university library will remain open 24/7 from December 15, 2024 to January 15, 2025. Additional study spaces and resources will be available. Students are encouraged to make use of the extended hours and available facilities. Please remember to bring your student ID for access.',
                'type' => 'update',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(3),
                'expires_at' => Carbon::now()->addDays(20),
                'file_paths' => null,
                'file_names' => null,
                'views' => 98,
                'downloads' => 0,
            ],
            [
                'title' => '💼 Career Fair 2025 - Register Now!',
                'content' => 'The annual Career Fair 2025 will be held on March 15, 2025 at the University Sports Complex. Over 50 leading companies will be participating. All students from all departments are encouraged to register and attend. Please bring your resume and dress professionally. Pre-registration is mandatory. Register online before March 10, 2025.',
                'type' => 'event',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(7),
                'expires_at' => Carbon::now()->addDays(50),
                'file_paths' => json_encode(['notices/2024/12/career-fair-guide.pdf']),
                'file_names' => json_encode(['Career_Fair_Guide_2025.pdf']),
                'views' => 132,
                'downloads' => 54,
            ],
            [
                'title' => '🏆 Student Innovation Challenge 2025',
                'content' => 'Calling all creative minds! The Student Innovation Challenge 2025 is now open for submissions. This is your chance to showcase your innovative ideas and projects. The winner will receive a cash prize of $5000 and a trophy. All students are eligible to participate. Submit your entries by February 28, 2025.',
                'type' => 'general',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(8),
                'expires_at' => Carbon::now()->addDays(45),
                'file_paths' => json_encode(['notices/2024/12/innovation-guidelines.pdf', 'notices/2024/12/submission-form.docx']),
                'file_names' => json_encode(['Innovation_Guidelines.pdf', 'Submission_Form.docx']),
                'views' => 87,
                'downloads' => 32,
            ],
            [
                'title' => '🌍 International Student Orientation Program',
                'content' => 'A special orientation program for international students will be conducted on January 20, 2025. All new international students are required to attend. The program will cover important information about campus life, visa regulations, academic policies, and cultural integration. Registration is mandatory. Please contact the International Student Office for more details.',
                'type' => 'important',
                'priority' => 'high',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(12),
                'expires_at' => Carbon::now()->addDays(35),
                'file_paths' => json_encode(['notices/2024/12/international-orientation.pdf']),
                'file_names' => json_encode(['International_Orientation_2025.pdf']),
                'views' => 112,
                'downloads' => 41,
            ],
            [
                'title' => '💰 Tuition Fee Payment Deadline Reminder',
                'content' => 'This is a reminder that the tuition fee payment deadline for the Spring 2025 semester is January 31, 2025. Payments can be made online through the student portal or at the finance office. Late payments will incur a penalty fee. If you have any questions regarding your fee structure, please contact the finance department.',
                'type' => 'urgent',
                'priority' => 'urgent',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(1),
                'expires_at' => Carbon::now()->addDays(30),
                'file_paths' => null,
                'file_names' => null,
                'views' => 203,
                'downloads' => 0,
            ],
            [
                'title' => '🎨 Art Exhibition: Student Showcase 2024',
                'content' => 'The Department of Fine Arts presents the Annual Student Art Exhibition 2024. The exhibition will be held from January 5-10, 2025 at the University Art Gallery. All students, faculty, and staff are invited. The exhibition will feature paintings, sculptures, digital art, and installations by our talented students. Free entry for all!',
                'type' => 'event',
                'priority' => 'low',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(15),
                'expires_at' => Carbon::now()->addDays(55),
                'file_paths' => json_encode(['notices/2024/12/art-exhibition-poster.jpg']),
                'file_names' => json_encode(['Art_Exhibition_Poster.jpg']),
                'views' => 76,
                'downloads' => 28,
            ],
            [
                'title' => '📝 Mid-Term Exam Schedule Released',
                'content' => 'The mid-term examination schedule for all departments has been released. Students are advised to check their respective department notice boards and the student portal for the detailed timetable. Please ensure you are aware of your exam dates and venues. Any conflicts or issues should be reported to the examination office immediately.',
                'type' => 'update',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(14),
                'expires_at' => Carbon::now()->addDays(20),
                'file_paths' => json_encode(['notices/2024/12/exam-schedule.pdf', 'notices/2024/12/exam-guidelines.pdf']),
                'file_names' => json_encode(['Exam_Schedule_2024.pdf', 'Exam_Guidelines.pdf']),
                'views' => 168,
                'downloads' => 73,
            ],
            [
                'title' => '🏅 Sports Day 2025 - Participation Registration',
                'content' => 'The Annual Sports Day 2025 will be held on February 15, 2025. Students interested in participating in various sports events are requested to register by February 1, 2025. Events include athletics, basketball, football, cricket, and more. Trophies and certificates will be awarded to winners. All students are encouraged to participate!',
                'type' => 'event',
                'priority' => 'low',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(6),
                'expires_at' => Carbon::now()->addDays(42),
                'file_paths' => json_encode(['notices/2024/12/sports-schedule.pdf']),
                'file_names' => json_encode(['Sports_Schedule_2025.pdf']),
                'views' => 94,
                'downloads' => 36,
            ],
            [
                'title' => '🔬 Research Grant Applications Open',
                'content' => 'The University Research Council is pleased to announce that applications for research grants are now open. Faculty members and research students are invited to submit proposals for funding. The deadline for submissions is February 28, 2025. Grants ranging from $5,000 to $50,000 are available. Guidelines and application forms are available at the research office.',
                'type' => 'important',
                'priority' => 'high',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(9),
                'expires_at' => Carbon::now()->addDays(48),
                'file_paths' => json_encode(['notices/2024/12/research-guidelines.pdf', 'notices/2024/12/application-form.pdf']),
                'file_names' => json_encode(['Research_Guidelines.pdf', 'Application_Form.pdf']),
                'views' => 145,
                'downloads' => 52,
            ],
            [
                'title' => '🎭 Cultural Festival 2025 - Call for Performances',
                'content' => 'The Cultural Festival 2025 is looking for talented students to perform. If you are interested in showcasing your talents in music, dance, drama, poetry, or any other art form, please register your performance by February 20, 2025. This is a great opportunity to share your culture and creativity with the university community.',
                'type' => 'general',
                'priority' => 'low',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(11),
                'expires_at' => Carbon::now()->addDays(52),
                'file_paths' => null,
                'file_names' => null,
                'views' => 65,
                'downloads' => 0,
            ],
            [
                'title' => '💻 IT Services Maintenance Notice',
                'content' => 'Please be informed that IT services will undergo scheduled maintenance on December 28, 2024 from 2:00 AM to 6:00 AM. During this time, the student portal, email services, and online learning platforms will be temporarily unavailable. We apologize for the inconvenience and appreciate your understanding. Please plan your activities accordingly.',
                'type' => 'update',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(4),
                'expires_at' => Carbon::now()->addDays(10),
                'file_paths' => null,
                'file_names' => null,
                'views' => 78,
                'downloads' => 0,
            ],
            [
                'title' => '🎯 Internship Opportunities - Winter 2025',
                'content' => 'Several internship opportunities are available for students during the Winter 2025 semester. Leading companies in various industries are offering internships in fields including engineering, business, IT, finance, and marketing. Visit the Career Services Office for a complete list of available positions and application procedures.',
                'type' => 'general',
                'priority' => 'medium',
                'status' => 'published',
                'is_pinned' => false,
                'published_at' => Carbon::now()->subDays(13),
                'expires_at' => Carbon::now()->addDays(47),
                'file_paths' => json_encode(['notices/2024/12/internship-list.pdf']),
                'file_names' => json_encode(['Internship_List_Winter2025.pdf']),
                'views' => 124,
                'downloads' => 61,
            ],
        ];

        // Insert notices
        foreach ($notices as $noticeData) {
            Notice::create([
                'title' => $noticeData['title'],
                'content' => $noticeData['content'],
                'type' => $noticeData['type'],
                'priority' => $noticeData['priority'],
                'status' => $noticeData['status'],
                'is_pinned' => $noticeData['is_pinned'],
                'published_at' => $noticeData['published_at'],
                'expires_at' => $noticeData['expires_at'],
                'file_paths' => $noticeData['file_paths'],
                'file_names' => $noticeData['file_names'],
                'views' => $noticeData['views'],
                'downloads' => $noticeData['downloads'],
                'created_by' => 1, // Assuming admin with ID 1 exists
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ ' . count($notices) . ' notices seeded successfully!');
    }
}